extends:
- airbnb-base
- plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
- typescript
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  node: true
  mocha: true
rules:
  indent:
  - error
  - 4
  no-param-reassign: 0
  no-use-before-define:
  - 2
  - functions: false
  no-return-await: 0
  max-len:
  - 1
  - 150
  camelcase: 1
  no-console: 2
  no-unused-expressions:
  - 2
  - allowTernary: true
  import/prefer-default-export:
    - 0
  no-underscore-dangle: off
settings:
  import/core-modules:
  - aws-sdk
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
    typescript: {}
